### ISSUE TITLE
TODO to finish this package

### ISSUE THREAD

**Issue by shylux** [4teamwork/ftw.openlayerhotfix#1]
Extranet with another explanation: https://extranet.4teamwork.ch/extern/0202-projekt-edubs-ict-basler-schulen/tracker-edubs/752
- [x] [Specify layer for jbot directory](https://github.com/4teamwork/ftw.openlayerhotfix/blob/master/ftw/openlayerhotfix/configure.zcml#L7)
- [x] Copy [OpenLayer.js](http://dev.openlayers.org/OpenLayers.js) into the jbot directory and give it the proper name to overwrite the OpenLayer.js in [collective.geo.openlayers](https://github.com/collective/collective.geo.openlayers/blob/3.1/src/collective/geo/openlayers/skins/geo_openlayers/OpenLayers.js)
- [x] Make sure it works and then make a release. (I never actually ran it)
- [x] Install `ftw.openlayerhotfix` in all the Products.
